--- #YAML:1.0
name:               WWW-Yahoo-InboundLinks
version:            0.07
abstract:           ~
author:
    - Ivan Baktsheev <dot.and.thing@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:            2.1
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
